
package com.elle.ProjectManager.presentation;

import com.elle.ProjectManager.database.DBConnection;
import com.elle.ProjectManager.database.SQL_Commands;
import com.elle.ProjectManager.logic.ReadWriteFiles;
import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JFileChooser;

/**
 *
 * @author Carlos Igreja
 */
public class CompIssuesWireFrame extends javax.swing.JFrame {

    private final String ALL = "All";  // used for the all option
    
    private SQL_Commands sql;
    private ReadWriteFiles rwFiles;
    
    /**
     * Creates new form CompIssuesWireFrame
     */
    public CompIssuesWireFrame() {
        initComponents();
        
        // initialize class variables
        sql = new SQL_Commands(DBConnection.getConnection());
        rwFiles = new ReadWriteFiles();
        
        // initialize all combo boxes
        initComboBoxes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaFileInformation = new javax.swing.JTextArea();
        labelProgrammer = new javax.swing.JLabel();
        labelApp = new javax.swing.JLabel();
        labelFromDB = new javax.swing.JLabel();
        labelToDB = new javax.swing.JLabel();
        cboxOpenCloseDB = new javax.swing.JComboBox<>();
        cboxFromDB = new javax.swing.JComboBox<>();
        cboxToDB = new javax.swing.JComboBox<>();
        cboxProgrammer = new javax.swing.JComboBox<>();
        cboxApp = new javax.swing.JComboBox<>();
        btnWriteToTextFile = new javax.swing.JButton();
        btnBrowse = new javax.swing.JButton();
        labelChooseFileLocation = new javax.swing.JLabel();
        labelDisplayPath = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textAreaFileInformation.setColumns(20);
        textAreaFileInformation.setRows(5);
        textAreaFileInformation.setText("\nID  Title   Description     \n------------------------\nnotes here\n\nSays you want dates?\nshould dates be included somewhere.\nasdf");
        jScrollPane1.setViewportView(textAreaFileInformation);

        labelProgrammer.setText("Programmer:");

        labelApp.setText("App:");

        labelFromDB.setText("From:");

        labelToDB.setText("To:");

        cboxOpenCloseDB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboxFromDB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboxToDB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboxProgrammer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboxProgrammer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxProgrammerActionPerformed(evt);
            }
        });

        cboxApp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnWriteToTextFile.setText("Write to Text File");

        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        labelChooseFileLocation.setText("Choose file location:");

        labelDisplayPath.setText("path of file displays here:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDisplayPath, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnWriteToTextFile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelChooseFileLocation)
                                .addGap(18, 18, 18)
                                .addComponent(btnBrowse, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelFromDB)
                                    .addComponent(labelToDB))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboxOpenCloseDB, 0, 152, Short.MAX_VALUE)
                                    .addComponent(cboxFromDB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboxToDB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelApp)
                                    .addComponent(labelProgrammer))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboxProgrammer, 0, 151, Short.MAX_VALUE)
                                    .addComponent(cboxApp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboxOpenCloseDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFromDB)
                    .addComponent(cboxFromDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelToDB)
                    .addComponent(cboxToDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProgrammer)
                    .addComponent(cboxProgrammer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelApp)
                    .addComponent(cboxApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelChooseFileLocation)
                    .addComponent(btnBrowse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelDisplayPath, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnWriteToTextFile)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // JFileChooser for choosing a file or directory
        JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new File("."));
        fc.setDialogTitle("File Chooser");
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        fc.showOpenDialog(this);
        String path = fc.getSelectedFile().getAbsolutePath();
        labelDisplayPath.setText(path);
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void cboxProgrammerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxProgrammerActionPerformed
        
    }//GEN-LAST:event_cboxProgrammerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompIssuesWireFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompIssuesWireFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompIssuesWireFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompIssuesWireFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompIssuesWireFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnWriteToTextFile;
    private javax.swing.JComboBox<String> cboxApp;
    private javax.swing.JComboBox<String> cboxFromDB;
    private javax.swing.JComboBox<String> cboxOpenCloseDB;
    private javax.swing.JComboBox<String> cboxProgrammer;
    private javax.swing.JComboBox<String> cboxToDB;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelApp;
    private javax.swing.JLabel labelChooseFileLocation;
    private javax.swing.JLabel labelDisplayPath;
    private javax.swing.JLabel labelFromDB;
    private javax.swing.JLabel labelProgrammer;
    private javax.swing.JLabel labelToDB;
    private javax.swing.JTextArea textAreaFileInformation;
    // End of variables declaration//GEN-END:variables

    private void initComboBoxes() {
        
        HashMap<String,ArrayList<Object>> map;
        
        // make sure the connection is open
        DBConnection.close();     // close old connection
        DBConnection.open();      // open new connection
        sql.setConnection(DBConnection.getConnection());    // set connection
        sql.createStatement(DBConnection.getConnection());  // create statement
        
        // Opened or Closed Dates
        cboxOpenCloseDB.removeAllItems();
        cboxOpenCloseDB.addItem("None");
        cboxOpenCloseDB.addItem("Opened Dates");
        cboxOpenCloseDB.addItem("Closed Dates");
        
        // App combobox
        map = sql.getDistinctColumnValues("issues", "app");
        cboxApp.removeAllItems();
        cboxApp.addItem(ALL);
        for(int i = 0; i < map.get("app").size(); i++){
            cboxApp.addItem(map.get("app").get(i).toString());
        }
        
        // Programmer combobox
        map = sql.getDistinctColumnValues("issues", "programmer");
        cboxProgrammer.removeAllItems();
        cboxProgrammer.addItem(ALL);
        for(int i = 0; i < map.get("programmer").size(); i++){
            cboxProgrammer.addItem(map.get("programmer").get(i).toString());
        }
    }
}
